env:
  browser: true
  es2020: true
extends:
  - plugin:react/recommended
  - airbnb-base
  - airbnb/rules/react
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/react
  - prettier/@typescript-eslint
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - prettier
rules:
  {
    import/no-unresolved: off,
    import/extensions: off,
    no-unused-expressions: off,
    react/jsx-filename-extension: off,
    react/button-has-type: off,
    '@typescript-eslint/explicit-module-boundary-types': off,
  }
